language: python
python:
  - "3.6"
before_install:
  - "pip install -U pip"
  - "python setup.py install"
  - "pip install -U setuptools wheel cython>=0.15.1"
install:
  - pip install -r requirements.txt
script:
  - pytest
